import os
os.chdir("J:/codex-work/LDCodex2")
content = open("crates/codex-plus-core/src/app_paths.rs", "r", encoding="utf-8").read()
count_dot = content.count("fn dot_char() -> String {")
count_cfg = content.count("#[cfg(target_os = \"macos\")]")
count_cfg_dup = content.count("#[cfg(target_os = \"macos\")]\n#[cfg(target_os = \"macos\")]")
count_const = content.count("const CODEX_PREFIX")
count_ver = content.count("OsStr::new(\"\\\\\")")
lines = content.split("\n")
print(f"fn dot_char count: {count_dot} (should be 1)")
print(f"#[cfg(target_os = \"macos\")] total: {count_cfg}")
print(f"Duplicate cfg lines: {count_cfg_dup} (should be 0)")
print(f"const CODEX_PREFIX: {count_const} (should be 0)")
print(f"VerQueryValueW: {count_ver} (should be >= 1)")
print(f"Total lines: {len(lines)}")
