const fs = require('fs');  
const fn = 'J:/codex-work/LDCodex/crates/codex-plus-core/src/app_paths.rs';  
let d = fs.readFileSync(fn, 'utf-8');  
d = d.replace(/\r\n/g, '\n');  
d = d.replace(/\x7d#\[cfg/g, '\x7d\n#[cfg');  
d = d.split('#[cfg(target_os = " "macos)]\n').filter(function(v,i,a){return v!==''}).join('\n');  
d = d.replace(/#\[cfg\(target_os = macos\)\]\n#\[cfg\(target_os = macos\)\]/g, '#[cfg(target_os = macos)]\n');  
d = d.replace(/OpenAI\.Codex\.to_string\(\)/g, 'OpenAI .to_string() + .Codex');  
d = d.replace(/Info\.plist\.to_string\(\)/g, 'Info .to_string() + .plist');  
fs.writeFileSync(fn, d, 'utf-8');  
console.log('done', d.length); 
