const fs = require('fs');
const p = 'J:\\codex-work\\LDCodex\\apps\\codex-plus-manager\\src\\App.tsx';
let c = fs.readFileSync(p, 'utf-8');
c = c.replace(/供应商配置/g, '模型配置');
c = c.replace('  { id: "zedRemote", label: "Zed 远程项目", icon: ExternalLink },\r\n', '');
c = c.replace('  { id: "userScripts", label: "脚本市场", icon: FileCode2 },\r\n', '');
c = c.replace('  { id: "recommendations", label: "推荐内容", icon: ExternalLink },\r\n', '');
c = c.replace('"zedRemote" | "userScripts" | "recommendations" | ', '');
c = c.replace('    zedRemote: "管理 Codex SSH 项目并加入 Zed workspace",\r\n', '');
c = c.replace('    userScripts: "内置和用户自定义脚本清单",\r\n', '');
c = c.replace('    recommendations: "赞助商推荐与普通推荐",\r\n', '');
c = c.replace('    if (next === "zedRemote") {\r\n      await refreshZedRemoteProjects(true);\r\n      return;\r\n    }\r\n', '');
c = c.replace('    if (next === "userScripts") {\r\n      await refreshScriptMarket(true);\r\n      return;\r\n    }\r\n', '');
c = c.replace('    if (next === "recommendations") await refreshAds(true);\r\n', '');
c = c.replace('          {route === "zedRemote" ? (\r\n            <ZedRemoteScreen projects={zedRemoteProjects} form={settingsForm} onFormChange={setSettingsForm} actions={actions} />\r\n          ) : null}\r\n', '');
c = c.replace('          {route === "userScripts" ? <UserScriptsScreen settings={settings} market={scriptMarket} actions={actions} /> : null}\r\n', '');
c = c.replace('          {route === "recommendations" ? <RecommendationsScreen ads={ads} actions={actions} /> : null}\r\n', '');
c = c.replace('const SCRIPT_MARKET_REPOSITORY_URL = "https://github.com/luoda2023/LDCodexScriptMarket";\r\n', '');
console.log('zedRemote:', (c.match(/zedRemote/g)||[]).length);
console.log('ScriptMarket:', (c.match(/ScriptMarket/g)||[]).length);
console.log('Supplier:', (c.match(/供应商/g)||[]).length);
c = c.replace(/\r\n\r\n\r\n/g, '\r\n\r\n');
fs.writeFileSync(p, c, 'utf-8');
console.log('OK');
