const fs = require('fs');  
const fn = 'J:/codex-work/LDCodex/crates/codex-plus-core/src/app_paths.rs';  
let d = fs.readFileSync(fn, 'utf-8');  
d = d.split('#[cfg(target_os = \" "macos\)]').join('___CFG___');  
d = d.split('___CFG___\\n___CFG___').join('___CFG___');  
d = d.split('___CFG___').join('#[cfg(target_os = \macos\)]');  
d = d.split('\OpenAI.Codex\.to_string()').join('\OpenAI\ .to_string() + \.Codex\');  
d = d.split('\Info.plist\.to_string()').join('\Info\ .to_string() + \.plist\');  
fs.writeFileSync(fn, d, 'utf-8');  
console.log('step2 done'); 
