const fs = require("fs");
const p = "J:\\codex-work\\LDCodex\\apps\\codex-plus-manager\\src\\App.tsx";
let c = fs.readFileSync(p, "utf-8");
c = c.replace(/\u4f9b\u5e94\u5546\u914d\u7f6e/g, "\u6a21\u578b\u914d\u7f6e");
c = c.replace('  { id: "zedRemote", label: "Zed \u8fdc\u7a0b\u9879\u76ee", icon: ExternalLink },\n', '');
c = c.replace('  { id: "userScripts", label: "\u811a\u672c\u5e02\u573a", icon: FileCode2 },\n', '');
c = c.replace('  { id: "recommendations", label: "\u63a8\u8350\u5185\u5bb9", icon: ExternalLink },\n', '');
c = c.replace('"zedRemote" | "userScripts" | "recommendations" | ', '');
c = c.replace('    zedRemote: "\u7ba1\u7406 Codex SSH \u9879\u76ee\u5e76\u52a0\u5165 Zed workspace",\n', '');
c = c.replace('    userScripts: "\u5185\u7f6e\u548c\u7528\u6237\u81ea\u5b9a\u4e49\u811a\u672c\u6e05\u5355",\n', '');
c = c.replace('    recommendations: "\u8d5e\u52a9\u5546\u63a8\u8350\u4e0e\u666e\u901a\u63a8\u8350",\n', '');
c = c.replace('    if (next === "zedRemote") {\n      await refreshZedRemoteProjects(true);\n      return;\n    }\n', '');
c = c.replace('    if (next === "userScripts") {\n      await refreshScriptMarket(true);\n      return;\n    }\n', '');
c = c.replace('    if (next === "recommendations") await refreshAds(true);\n', '');
c = c.replace('          {route === "zedRemote" ? (\n            <ZedRemoteScreen projects={zedRemoteProjects} form={settingsForm} onFormChange={setSettingsForm} actions={actions} />\n          ) : null}\n', '');
c = c.replace('          {route === "userScripts" ? <UserScriptsScreen settings={settings} market={scriptMarket} actions={actions} /> : null}\n', '');
c = c.replace('          {route === "recommendations" ? <RecommendationsScreen ads={ads} actions={actions} /> : null}\n', '');
c = c.replace('const SCRIPT_MARKET_REPOSITORY_URL = "https://github.com/luoda2023/LDCodexScriptMarket";\n', '');
console.log("zedRemote:", (c.match(/zedRemote/g)||[]).length);
console.log("ScriptMarket:", (c.match(/ScriptMarket/g)||[]).length);
console.log("Supplier:", (c.match(/\u4f9b\u5e94\u5546/g)||[]).length);
fs.writeFileSync(p, c, "utf-8");
console.log("Saved");
